# Generated by Django 4.0.6 on 2022-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_grounddetails_alter_admin_email_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grounddetails',
            name='defaultPrice',
            field=models.IntegerField(null=True),
        ),
    ]
