# Generated by Django 4.0.6 on 2022-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_cloasingtime_turfdetails_closingtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turfdetails',
            old_name='aminities',
            new_name='amenities',
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='country',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='pincode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfdetails',
            name='state',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
