# Generated by Django 4.0.6 on 2022-10-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_aminities_turfdetails_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingtime',
            name='coachingFlag',
        ),
    ]
